# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ImmersityPortalBackend-Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://immersityxr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dcd09d95ba9c44ae8fca70ff0ef6834e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1535b149cae749b6b8ef256edaf6e91c }}

    - name: Build back end with environment secrets
      run: |
        cd ./backend
        pwd
        echo "${{ secrets.BUILD_BACKEND_ENV_SCRIPT }}" > setenv.sh
        echo "${{ secrets.BUILD_BACKEND_CONFIG }}" > server/config.js
        docker build . -t immersityxr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcd09d95ba9c44ae8fca70ff0ef6834e }}/immersity-portal-backend/immersity-portal-backend:${{ github.sha }}
    
    - name: Push container image to registry
      run: |
        docker push immersityxr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcd09d95ba9c44ae8fca70ff0ef6834e }}/immersity-portal-backend/immersity-portal-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ImmersityPortalBackend-Test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_df8ba1adf17e44d9930dea21f91b6a80 }}
        images: 'immersityxr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcd09d95ba9c44ae8fca70ff0ef6834e }}/immersity-portal-backend/immersity-portal-backend:${{ github.sha }}'